#!/bin/sh

bspc config border_width 2
bspc config window_gap -2
bspc config top_padding 34
bspc config bottom_padding 2
bspc config left_padding 2
bspc config right_padding 2

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config single_monocle false
bspc config initial_polarity first_child
bspc config pointer_follows_monitor true

bspc monitor DVI-I-2 -d 1 2 3 4 5 6 7
bspc monitor DVI-I-1 -d 8

bspc config focused_border_color "#FFFFFF"

nvidia-settings --assign "CurrentMetaMode=DPY-2: nvidia-auto-select @1920x1080 +0+768 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0, ForceFullCompositionPipeline=On}, DPY-1: nvidia-auto-select @1360x768 +280+0  {ViewPortIn=1360x768, ViewPortOut=1360x768+0+0, ForceFullCompositionPipeline=On}"
feh --bg-scale pictures/lfkL48Z.jpg
tint2 &
bspc monitor -f '^2'
bspc monitor -f '^1'
